/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketbooking;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author gurpreet9001
 */
public class all_tickets extends javax.swing.JInternalFrame implements myvariables {

    /**
     * Creates new form all_tickets
     */
    public all_tickets() {
        initComponents();
        
                try
 {
 Connection myconnection1;
 myconnection1=DriverManager.getConnection(PATH+PLACE, USERNAME, PASS);
 
 try
 {
    String myquery1="select distinct(city) from ticket_booked";
    PreparedStatement mystatement1=myconnection1.prepareStatement(myquery1);
    ResultSet myresult1=mystatement1.executeQuery();
    
    if(myresult1.next()){
    do{
    citybox.addItem(myresult1.getString("city"));
    }while(myresult1.next());
    }
  
    citybox.setSelectedIndex(0);
   
 
 }
 catch(Exception e)
 {
    JOptionPane.showMessageDialog(rootPane, "Error in Query 1 " + e.getMessage());
 }
 finally
 {
    myconnection1.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
        
        
   try
 {
 Connection myconnection;
 myconnection=DriverManager.getConnection(PATH+PLACE, USERNAME, PASS);
 
 try
 {
    String myquery="select * from ticket_booked";
    PreparedStatement mystatement=myconnection.prepareStatement(myquery);
    ResultSet myresult=mystatement.executeQuery();
    
    if(myresult.next()){
      DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
        String city,theater,movie,username,no_of_tickets,date,price,total,showdate,time;
        do{
    city=myresult.getString("city");
    theater=myresult.getString("theater");
    movie=myresult.getString("movie");
    username=myresult.getString("username");
    no_of_tickets=myresult.getString("no_of_tickets");
    date=myresult.getString("date");
    price=myresult.getString("price");
    showdate=myresult.getString("showdate");
    total=myresult.getString("total");
    time=myresult.getString("time");
    
    mymodel.addRow(new Object[]{city,theater,movie,username,no_of_tickets,date,price,total,showdate,time});
    }while(myresult.next());
    
    }
    
 
 }
 catch(Exception e)
 {
    JOptionPane.showMessageDialog(rootPane, "Error in Query 2 " + e.getMessage());
 }
 finally
 {
    myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        citybox = new javax.swing.JComboBox<>();
        theaterbox = new javax.swing.JComboBox<>();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        moviebox = new javax.swing.JComboBox<>();
        databutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        databutton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ticket List");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City", "Theater", "Movie", "Username", "No_of_tickets", "Book Date", "Price", "Total", "Show Date", "time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        citybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose City" }));
        citybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityboxActionPerformed(evt);
            }
        });

        theaterbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose theater name" }));
        theaterbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theaterboxActionPerformed(evt);
            }
        });

        jLabel1.setText(" From                                                      To");

        moviebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose movie name" }));
        moviebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieboxActionPerformed(evt);
            }
        });

        databutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/search.png"))); // NOI18N
        databutton.setText("Get Data");
        databutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("DATE");

        databutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/printer.png"))); // NOI18N
        databutton1.setText("Print");
        databutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(citybox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(theaterbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moviebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(85, 85, 85)
                .addComponent(databutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(databutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moviebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(theaterbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(databutton)
                            .addComponent(databutton1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void databuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databuttonActionPerformed
         try
 {
 Connection myconnection;
 myconnection=DriverManager.getConnection(PATH+PLACE, USERNAME, PASS);
 
 try
 {
    String myquery="select * from ticket_booked where city=? and theater=? and movie=? and date between ? and ?";
     PreparedStatement mystatement=myconnection.prepareStatement(myquery);
                mystatement.setString(2, theaterbox.getSelectedItem().toString());
                mystatement.setString(1, citybox.getSelectedItem().toString());
                mystatement.setString(3, moviebox.getSelectedItem().toString());
                 SimpleDateFormat myformat=new SimpleDateFormat("yyyy-MM-dd");
                mystatement.setString(4, myformat.format(date1.getDate()));
                SimpleDateFormat myformat1=new SimpleDateFormat("yyyy-MM-dd");
                mystatement.setString(5, myformat1.format(date2.getDate()));
                
         ResultSet myresult=mystatement.executeQuery();
                
          
    if(myresult.next()){
      DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
        String city,theater,movie,username,no_of_tickets,date,price,total,showdate,time;
        mymodel.setRowCount(0);
        do{
    city=myresult.getString("city");
    theater=myresult.getString("theater");
    movie=myresult.getString("movie");
    username=myresult.getString("username");
    no_of_tickets=myresult.getString("no_of_tickets");
    date=myresult.getString("date");
    price=myresult.getString("price");
    showdate=myresult.getString("showdate");
    total=myresult.getString("total");
    time=myresult.getString("time");
    
    mymodel.addRow(new Object[]{city,theater,movie,username,no_of_tickets,date,price,total,showdate,time});
    }while(myresult.next());
    
    }
    
      
                    theaterbox.setSelectedIndex(0);
                    citybox.setSelectedIndex(0);
                    moviebox.setSelectedIndex(0);
                    date1.setDate(null);
                     date2.setDate(null);
              
    
 
 }
 catch(Exception e)
 {
    JOptionPane.showMessageDialog(rootPane, "Error in Query 2 " + e.getMessage());
 }
 finally
 {
    myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
    }//GEN-LAST:event_databuttonActionPerformed

    private void movieboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieboxActionPerformed

    private void theaterboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theaterboxActionPerformed
                      try
 {
 Connection myconnection;
 myconnection=DriverManager.getConnection(PATH+PLACE, USERNAME, PASS);
 
 try
 {
    String myquery="select movie from movies where theatername=?";
    PreparedStatement mystatement=myconnection.prepareStatement(myquery);
    mystatement.setString(1,theaterbox.getSelectedItem().toString());
    ResultSet myresult=mystatement.executeQuery();
    
    
    
    
    
    if(myresult.next()){
        moviebox.removeAllItems();
        moviebox.addItem("Choose movies now");
    do{
    moviebox.addItem(myresult.getString("movie"));
    }while(myresult.next());
    
    }
      else     
    moviebox.setSelectedIndex(0);
    
 
 }
 catch(Exception e)
 {
    //JOptionPane.showMessageDialog(rootPane, "Error in Query 2 " + e.getMessage());
 }
 finally
 {
    myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
                                             
 
    }//GEN-LAST:event_theaterboxActionPerformed

    private void cityboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityboxActionPerformed
                       try
 {
 Connection myconnection;
 myconnection=DriverManager.getConnection(PATH+PLACE, USERNAME, PASS);
 
 try
 {
    String myquery="select distinct(theater) from ticket_booked where city=?";
    PreparedStatement mystatement=myconnection.prepareStatement(myquery);
    mystatement.setString(1,citybox.getSelectedItem().toString());
    ResultSet myresult=mystatement.executeQuery();
    
    
    
    
    
    if(myresult.next()){
        theaterbox.removeAllItems();
        theaterbox.addItem("Choose theater now");
    do{
    theaterbox.addItem(myresult.getString("theater"));
    }while(myresult.next());
    
    }
           
    theaterbox.setSelectedIndex(0);
    
 
 }
 catch(Exception e)
 {
    //JOptionPane.showMessageDialog(rootPane, "Error in Query 2 " + e.getMessage());
 }
 finally
 {
    myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
 }
    }//GEN-LAST:event_cityboxActionPerformed

    private void databutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databutton1ActionPerformed
        MessageFormat headerFormat = new MessageFormat("Booked Tickets");
        MessageFormat footerFormat = new MessageFormat("Page {0}");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
        } catch (PrinterException ex) {
            Logger.getLogger(all_tickets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_databutton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> citybox;
    private javax.swing.JButton databutton;
    private javax.swing.JButton databutton1;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> moviebox;
    private javax.swing.JComboBox<String> theaterbox;
    // End of variables declaration//GEN-END:variables
}
