/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketbooking;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
/**
 *
 * @author gurpreet9001
 */
public class deleteticket extends javax.swing.JInternalFrame implements myvariables {

    /**
     * Creates new form deleteticket
     */
    public deleteticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        city = new javax.swing.JLabel();
        theater = new javax.swing.JLabel();
        movie = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        userID = new javax.swing.JLabel();
        useridbox = new javax.swing.JTextField();
        tickets1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        citybox = new javax.swing.JLabel();
        theaterbox = new javax.swing.JLabel();
        moviebox = new javax.swing.JLabel();
        ticketbox = new javax.swing.JLabel();
        tickets2 = new javax.swing.JLabel();
        datebox = new javax.swing.JLabel();
        timebox = new javax.swing.JLabel();
        tickets3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cancel Ticket");

        city.setText("City");

        theater.setText("Theater");

        movie.setText("Movie");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/search.png"))); // NOI18N
        jButton1.setText("Search Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        userID.setText("Unique UserID");

        tickets1.setText("No. of Tickets");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/]wq.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        citybox.setText("...");

        theaterbox.setText("...");

        moviebox.setText("...");

        ticketbox.setText("...");

        tickets2.setText("Date");

        datebox.setText("...");

        timebox.setText("...");

        tickets3.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(city)
                    .addComponent(movie)
                    .addComponent(theater)
                    .addComponent(userID)
                    .addComponent(tickets1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tickets3)
                        .addComponent(tickets2)))
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(useridbox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ticketbox, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(datebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(citybox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(moviebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(theaterbox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userID)
                    .addComponent(useridbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theater)
                    .addComponent(theaterbox))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movie)
                    .addComponent(moviebox))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city)
                    .addComponent(citybox))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tickets1)
                    .addComponent(ticketbox))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tickets2)
                    .addComponent(datebox))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timebox)
                    .addComponent(tickets3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try
 {
 Connection myconnection = DriverManager.getConnection(PATH+PLACE, USERNAME,PASS); 
 
 try
 {
 String myquery="select * from ticket_booked where username=?";
 PreparedStatement mystatement = myconnection.prepareStatement(myquery);
 mystatement.setString(1, useridbox.getText());
 ResultSet myresult=mystatement.executeQuery();
 
 if(myresult.next())
 {
     jButton2.setEnabled(true);
 citybox.setText(myresult.getString("city"));
  theaterbox.setText(myresult.getString("theater"));
   moviebox.setText(myresult.getString("movie"));
 ticketbox.setText(myresult.getString("no_of_tickets"));
   datebox.setText(myresult.getString("date"));
   timebox.setText(myresult.getString("time"));


 }
 else
 {
 JOptionPane.showMessageDialog(rootPane,"Wrong User ID");
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "7 Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int answer = JOptionPane.showConfirmDialog(rootPane, 
 "Do you really want to delete?", "Are you sure?", 
 JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
 
 if(answer==JOptionPane.YES_OPTION)
 {
 try
 {
 Connection myconnection = DriverManager.getConnection(PATH+PLACE, USERNAME,PASS); 
 
 try
 {
 String myquery="delete from ticket_booked where username=?";
 PreparedStatement mystatement = myconnection.prepareStatement(myquery);
 mystatement.setString(1, useridbox.getText());
 
 if(mystatement.executeUpdate()>0)
 {
 JOptionPane.showMessageDialog(rootPane,"Deleted Successfully");
 ticketbox.setText("");
 citybox.setText("");
 theaterbox.setText("");
   moviebox.setText("");
   useridbox.setText("");
   datebox.setText("");
   timebox.setText("");

 } 
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "2 Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }
 }
         
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    private javax.swing.JLabel citybox;
    private javax.swing.JLabel datebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel movie;
    private javax.swing.JLabel moviebox;
    private javax.swing.JLabel theater;
    private javax.swing.JLabel theaterbox;
    private javax.swing.JLabel ticketbox;
    private javax.swing.JLabel tickets1;
    private javax.swing.JLabel tickets2;
    private javax.swing.JLabel tickets3;
    private javax.swing.JLabel timebox;
    private javax.swing.JLabel userID;
    private javax.swing.JTextField useridbox;
    // End of variables declaration//GEN-END:variables
}
