/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketbooking;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;

/**
 *
 * @author gurpreet9001
 */
public class updateticket extends javax.swing.JInternalFrame implements myvariables {

    /**
     * Creates new form updateticket
     */
    public updateticket() {
        initComponents();
        java.util.Date obj=new java.util.Date();
        SimpleDateFormat myformat=new SimpleDateFormat("yyyy-MM-dd");
        datebox.setText(myformat.format(obj));
        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userID = new javax.swing.JLabel();
        useridbox = new javax.swing.JTextField();
        ticketbox = new javax.swing.JTextField();
        tickets1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        movielabel = new javax.swing.JLabel();
        userID3 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        tickets2 = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        tickets3 = new javax.swing.JLabel();
        datebox = new javax.swing.JLabel();
        update = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Update Ticket Status");

        userID.setText("Unique UserID");

        tickets1.setText("No. of Tickets");

        date.setText("Updated Date");

        movielabel.setText("...");

        userID3.setText("Movie");

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/search.png"))); // NOI18N
        search.setText("Search Details");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        tickets2.setText("Date");

        datelabel.setText("...");

        timelabel.setText("...");

        tickets3.setText("Time");

        datebox.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(userID)
                                .addGap(62, 62, 62)
                                .addComponent(useridbox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tickets2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(search))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tickets1)
                            .addComponent(date)
                            .addComponent(tickets3)
                            .addComponent(userID3))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movielabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticketbox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userID)
                    .addComponent(useridbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tickets2)
                    .addComponent(datelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tickets3)
                    .addComponent(timelabel))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userID3)
                    .addComponent(movielabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ticketbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tickets1))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(datebox))
                .addGap(69, 69, 69))
        );

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/add.png"))); // NOI18N
        update.setText("Update");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(update))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
    try
 {
 Connection myconnection = DriverManager.getConnection(PATH+PLACE, USERNAME,PASS); 
 
 try
 {
 String myquery="update ticket_booked set tickets=?"
 + " where id=?";
 PreparedStatement mystatement = myconnection.prepareStatement(myquery);
 
 mystatement.setString(2, useridbox.getText());
 mystatement.setString(1, ticketbox.getText());
 
 if(mystatement.executeUpdate()>0)
 {
 JOptionPane.showMessageDialog(rootPane,"Updated Successfully");
 }
 else
 {
 JOptionPane.showMessageDialog(rootPane,"Sorry, some problem occured");
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "1 Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }
    }//GEN-LAST:event_updateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
         try
 {
 Connection myconnection = DriverManager.getConnection(PATH+PLACE, USERNAME,PASS); 
 
 try
 {
 String myquery="select * from ticket_booked where id=?";
 PreparedStatement mystatement = myconnection.prepareStatement(myquery);
 mystatement.setString(1, useridbox.getText());
 ResultSet myresult=mystatement.executeQuery();
 
 if(myresult.next())
 {
     update.setEnabled(true);
 ticketbox.setText(myresult.getString("tickets"));
 movielabel.setText(myresult.getString("movie"));
 datelabel.setText(myresult.getString("showdate"));
 timelabel.setText(myresult.getString("showtime"));
 }
 else
 {
 JOptionPane.showMessageDialog(rootPane,"Wrong User ID");
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "7 Error in Query due to " + e.getMessage());
 }
 finally
 {
 myconnection.close();
 }
 }
 catch(Exception e)
 {
 JOptionPane.showMessageDialog(rootPane, "Error in Connection due to " + e.getMessage());
 }
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel datebox;
    private javax.swing.JLabel datelabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel movielabel;
    private javax.swing.JButton search;
    private javax.swing.JTextField ticketbox;
    private javax.swing.JLabel tickets1;
    private javax.swing.JLabel tickets2;
    private javax.swing.JLabel tickets3;
    private javax.swing.JLabel timelabel;
    private javax.swing.JButton update;
    private javax.swing.JLabel userID;
    private javax.swing.JLabel userID3;
    private javax.swing.JTextField useridbox;
    // End of variables declaration//GEN-END:variables
}
